### ISSUE TITLE
White Right line on Small Screens

### ISSUE THREAD

**Issue by berniemaxima** [cusec/2019#2]
Gotta love responsiveness.

**Comment by berniemaxima** [comment]
Appears at 575px. Wonderful.

**Comment by migueog** [comment]
@berniemaxima Is this the white right line that you're talking about? -> 
<img width="1440" alt="screen shot 2018-10-31 at 9 47 13 am" src="https://user-images.githubusercontent.com/2801551/47792224-f4f92d80-dcf1-11e8-82dd-d67db48e1461.png">

 I was able to fix this by adding `margin: 0 auto`.

<img width="1440" alt="screen shot 2018-10-31 at 9 49 02 am" src="https://user-images.githubusercontent.com/2801551/47792353-35f14200-dcf2-11e8-8aab-33fac91a57b4.png">

My bad for jumping in on this issue. Just wanted to help <3

**Comment by berniemaxima** [comment]
Woaaaaa GENIUS. hahaha no no please, I'll never be upset at someone who makes my code better. THANKS so much, Miguel, I'll try it out.

**Comment by migueog** [comment]
@berniemaxima Let me know if it works :) I wasn't able to build the project locally so idk 🤷‍♂️

**Comment by berniemaxima** [comment]
@migueog Woaa seems to be working. I'll have to try it out on different browsers/OSes. You're like Jesus's second coming here. I think I lost like 2 hours yesterday trying to figure this out. Thanks a billion, <3 !!! And yea, I should definitely write up some doc on how to run, build and deploy the app. It'd save up some time to whoever wants to help!

**Comment by migueog** [comment]
@berniemaxima All good my dude. Happy to help.
